apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portal-shell.fullversionname" . }}
  labels:
    {{- include "portal-shell.labels" . | nindent 4 }}
data:
  {{- $currentScope := .}}
  {{- range $path, $_ :=  .Files.Glob  "config-files/*.json" }}
    {{- if not (hasKey $.Values.config.files (base $path)) }}
      {{- base $path | nindent 2 }}: |-
        {{- with $currentScope}}
          {{- tpl (.Files.Get $path) $ | nindent 4}}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- if $.Values.config.files }}
    {{- $.Values.config.files | toYaml | nindent 2 }}
  {{- end }}



